### ISSUE TITLE
[Bug]: towhee.api.as_function() object has no attribute '__name__'

### ISSUE THREAD

**Issue by shiyu22** [towhee-io/towhee#1489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run towhee pipeline with function mode in gradio:
```python
import towhee
with towhee.api() as api:
    towhee_function = (
        api.image_text_embedding.clip(model_name='clip_vit_b32',modality='text')
            .tensor_normalize()
            .as_function()
    )

import gradio

interface = gradio.Interface(towhee_function, 
                             gradio.inputs.Textbox(lines=1),
                             gradio.outputs.Textbox()
                            )

interface.launch(inline=True, share=True)
```
And got the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/pp/b5th1n0d2_9blg9wk9kt4j2c0000gn/T/ipykernel_84342/70903374.py in <module>
      1 import gradio
      2 
----> 3 interface = gradio.Interface(towhee_function, 
      4                              gradio.inputs.Textbox(lines=1),
      5                              gradio.outputs.Textbox()

~/miniconda3/envs/dev-towhee/lib/python3.8/site-packages/gradio/interface.py in __init__(self, fn, inputs, outputs, examples, cache_examples, examples_per_page, live, interpretation, num_shap, title, description, article, thumbnail, theme, css, allow_flagging, flagging_options, flagging_dir, flagging_callback, analytics_enabled, _repeat_outputs_per_model, **kwargs)
    250         self.predict = fn
    251         self.predict_durations = [[0, 0]] * len(fn)
--> 252         self.function_names = [func.__name__ for func in fn]
    253         self.__name__ = ", ".join(self.function_names)
    254 

~/miniconda3/envs/dev-towhee/lib/python3.8/site-packages/gradio/interface.py in <listcomp>(.0)
    250         self.predict = fn
    251         self.predict_durations = [[0, 0]] * len(fn)
--> 252         self.function_names = [func.__name__ for func in fn]
    253         self.__name__ = ", ".join(self.function_names)
    254 

AttributeError: '_Wrapper' object has no attribute '__name__'
```

But the above code works with towhee0.7.

### Expected Behavior

Successfully run it with the latest towhee code.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```
