### ISSUE TITLE
[Bug]: module 'towhee' has no attribute 'runtime'

### ISSUE THREAD

**Issue by xijiz** [towhee-io/towhee#2635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

环境：MacOS、python3.6、towhee=1.1.1

执行以下代码：

```python
from towhee import pipeline


embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
outs = embedding_pipeline(wav_path)
embeds = outs[0][0]
```

得到报错：

```plain
AttributeError                            Traceback (most recent call last)
<ipython-input-1-74c48a15fbd4> in <module>
----> 1 from towhee import pipeline
      2 
      3 
      4 embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
      5 outs = embedding_pipeline(wav_path)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/towhee/__init__.py in <module>
     18 import sys
     19 
---> 20 from towhee.runtime import register, pipe, ops, accelerate, AutoConfig, AutoPipes
     21 from towhee.serve.triton import triton_client
     22 from towhee.utils.lazy_import import LazyImport

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/towhee/runtime/__init__.py in <module>
     16 from .factory import ops, register
     17 from .pipeline import Pipeline as pipe
---> 18 from .auto_pipes import AutoPipes
     19 from .auto_config import AutoConfig
     20 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/towhee/runtime/auto_pipes.py in <module>
     20 
     21 
---> 22 import towhee.runtime.pipeline_loader as pipe_loader
     23 from towhee.utils.log import engine_log
     24 

AttributeError: module 'towhee' has no attribute 'runtime'

```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
The versions after 1.0 have rewritten the relevant interfaces. The latest usage of the audio pipeline： https://towhee.io/towhee/audio-embedding

**Comment by xijiz** [comment]
> The versions after 1.0 have rewritten the relevant interfaces. The latest usage of the audio pipeline： https://towhee.io/towhee/audio-embedding

<img width="1097" alt="image" src="https://github.com/towhee-io/towhee/assets/12234085/51ddbdf5-c07d-4a99-be5d-0f0e304bfb6c">

**Comment by xijiz** [comment]
> The versions after 1.0 have rewritten the relevant interfaces. The latest usage of the audio pipeline： https://towhee.io/towhee/audio-embedding

最新的用法还是存在问题

**Comment by junjiejiangjjj** [comment]
It is possible that some third-party libraries that Towhee depends on no longer support Python 3.6. Try using Python 3.7 or newer versions. It works OK in Python 3.7.
