### ISSUE TITLE
[Documentation]: Conda install Towhee via the `towhee-io` channel but v0.4

### ISSUE THREAD

**Issue by shiyu22** [towhee-io/towhee#2127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

https://docs.towhee.io/Getting%20Started/install/#installing-towhee-with-conda

When I install towhee via `conda install -c towhee-io towhee`, it will install `towhee0.4.0`. Does the latest version in the [default channel](https://anaconda.org/conda-forge/towhee)?

**Comment by binbinlv** [comment]
@shiyu22 
The channel is not right, please use channel "conda-forge".

conda install -c conda-forge towhee

**Comment by shiyu22** [comment]
> @shiyu22 The channel is not right, please use channel "conda-forge".
> 
> conda install -c conda-forge towhee

It works in my Mac, but still towhee0.4 in Ubuntu.

**Comment by SuperSupeng** [comment]
When I use the command `pip install towhee towhee.models`, it occurs error in MacOS
```
In file included from src/blob.c:30:
  src/blob.h:33:10: fatal error: 'git2.h' file not found
  #include <git2.h>
           ^~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pygit2
Failed to build pygit2
ERROR: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
```

**Comment by SuperSupeng** [comment]
BTW, when the python version is 3.6, `conda install -c conda-forge towhee` will take a long time to prepare the environment

**Comment by binbinlv** [comment]
> When I use the command `pip install towhee towhee.models`, it occurs error in MacOS
> 
> ```
> In file included from src/blob.c:30:
>   src/blob.h:33:10: fatal error: 'git2.h' file not found
>   #include <git2.h>
>            ^~~~~~~~
>   1 error generated.
>   error: command 'gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for pygit2
> Failed to build pygit2
> ERROR: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
> ```

@SuperSupeng 
Thanks for the issue.

@Chiiizzzy 

Could you please take a look here? Thanks.

**Comment by Chiiizzzy** [comment]
> 



> When I use the command `pip install towhee towhee.models`, it occurs error in MacOS
> 
> ```
> In file included from src/blob.c:30:
>   src/blob.h:33:10: fatal error: 'git2.h' file not found
>   #include <git2.h>
>            ^~~~~~~~
>   1 error generated.
>   error: command 'gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for pygit2
> Failed to build pygit2
> ERROR: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
> ```

Hi, @SuperSupeng, which version of python are you using? `pygit2` supports 3.7 - 3.10 only, If you are using python 3.6, `pygit2` will fail to install. If you are using python 3.7+, could you please try:
```shell
$ brew update
$ brew install libgit2
$ pip3 install pygit2
``` 
You can refer to https://www.pygit2.org/install.html#installing-on-os-x

**Comment by SuperSupeng** [comment]
> 

I use python 3.6 version. Suggest to change the description in the documentation to python 3.7 and above.
